server:
  port: 9090

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted: "*"

  mail:
    host: smtp.example.com
    port: 587
    username: user@example.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true